version: 0.2

env:
  variables:
    # Github username of the forked repo on which to make builds
    GITHUBUSERNAME: Ephylouise

phases:
  install:
    commands:
      - architecture=""
      # Same buildspec for different architectures - detect the architecture here and rename the artifacts accordingly
      - case $(uname -m) in
           x86_64)
             architecture="amd64"
           ;;
           aarch64)
             architecture="arm64"
           ;;
        esac

      # Install GO to ensure version is up-to-date on OS
      - sudo rm -rf "/root/.goenv"
      - sudo yum install golang -y

      # Set evironment GOROOT based on architecture
      - if [[ "$(uname -m)" == "x86_64" ]]; then
          export GOROOT=/usr/bin/go
        else
          export GOROOT=/usr/local/go/bin/go
            fi
      - which go | tee -a $BUILD_LOG
      - go version | tee -a $BUILD_LOG
      
  build:
    commands:
      - go version
      - echo "build_id = $CODEBUILD_LOG_PATH" 2>&1 | tee -a $BUILD_LOG
      - echo "Building agent image" 2>&1 | tee -a $BUILD_LOG
      - AGENT_VERSION=$(cat VERSION)
      - AMZN_LINUX_2_RPM="ecs-init-${AGENT_VERSION}-1.amzn2.x86_64.rpm"
      - echo $(pwd) 2>&1 | tee -a $BUILD_LOG

      # Path readjustment for codebuild testing with fork and setting GOPATH appropriately
      - cd ../../../..
      - export GOPATH=$GOPATH:$(pwd)
      - cd src/github.com
      - |
        if [[ $GITHUBUSERNAME != "aws" ]]; then
          mv $GITHUBUSERNAME aws
        fi
      - cd aws/amazon-ecs-agent

      # Build Amazon Linux 2 RPM
      - GO111MODULE=auto
      - make amazon-linux-rpm-integrated 2>&1 | tee -a $BUILD_LOG
      - ls
      
      # Rename artifacts for architecture
      - |
        if [[ $architecture == "arm64" ]] ; then
          AMZN_LINUX_2_RPM="ecs-init-${AGENT_VERSION}-1.amzn2.aarch64.rpm"
        fi

  post_build:
    commands:

artifacts:
  files:
    - $AMZN_LINUX_2_RPM
  name: $CODEBUILD_RESOLVED_SOURCE_VERSION

